LOCAL_PATH := $(call my-dir)

include $(CLEAR_VARS)

LOCAL_C_INCLUDES += $(LOCAL_PATH)/../lua
LOCAL_MODULE     := unix
LOCAL_SRC_FILES  := unix.c \
		unix-getopt.c
		
LOCAL_STATIC_LIBRARIES := LXCLuaCore

LOCAL_CFLAGS += -DANDROID -UHAVE_SIGTIMEDWAIT -UHAVE_GETIFADDRS -UHAVE_GETGRGID_R -UHAVE_GETGRNAM_R -UHAVE_FMEMOPEN -UHAVE_LOCKF -UHAVE_MKFIFOAT -UHAVE_PROGRAM_INVOCATION_SHORT_NAME -UHAVE_STRUCT_STAT_ST_ATIMESPEC -UHAVE_STRUCT_STAT_ST_MTIMESPEC -UHAVE_STRUCT_STAT_ST_CTIMESPEC -UHAVE_STRUCT_STAT_ST_ATIM -UHAVE_STRUCT_STAT_ST_MTIM -UHAVE_STRUCT_STAT_ST_CTIM\

LOCAL_LDLIBS += -L$(SYSROOT)/usr/lib -llog -ldl

include $(BUILD_SHARED_LIBRARY)
